import { Inter } from 'next/font/google';
import './globals.css';
import TransitionProvider from '@/components/TransitionProvider';
import CookieBanner from '@/components/CookieBanner';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import { locales } from '@/config';  // Импортируйте локали
import { notFound } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Business site',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }) {
  const { locale } = params;

  // Проверка на допустимость локали
  if (!locales.includes(locale)) {
    notFound(); // Если локаль не допустима, вызвать notFound()
  }

  let messages;
  try {
    messages = await getMessages();  // Обратите внимание на возможные ошибки с импортом
  } catch (error) {
    console.error('Ошибка при загрузке сообщений:', error);
    notFound(); // Можно также вызвать notFound() здесь
  }

  return (
    <html lang={locale}>
      <body className={`${inter.className} min-h-screen h-screen flex flex-col`}>
        <NextIntlClientProvider messages={messages}>
          <TransitionProvider>
            <CookieBanner />
            {children}
          </TransitionProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
